# PROJET PYTHON + SQL

travail de groupe

In [7]:
import pandas as pd

In [8]:
import squarify
import matplotlib.pyplot as plt

In [9]:
import seaborn as sns
import plotly.express as px
import ipywidgets as widgets

In [10]:
online_retail = pd.read_csv('online_retail.csv')

#### df.shape()
#### df.info() - On cherche à comprendre quelle est la structure du Dataframe
#### df.head() - On cherche à comprendre à quoi ressemblent les données, avoir une première inspection visuelle
#### df.isna().sum() - On cherche à comprendre combien de données sont manquantes?
#### df.nunique() - On cherche à comprendre combien existe-t-il de valeurs différentes dans chaque colonne
#### df.describe() - On cherche à comprendre comment se comportent les variable numériques
#### df.duplicated().sum() - Vérifier combien on a des doublons

#### InvoiceNo : Numéro de facture. Variable nominale ; nombre entier à 6 chiffres attribué de manière unique à chaque transaction. Si ce code commence par la lettre « c », il indique une annulation.
#### StockCode : Code du produit (article). Variable nominale ; nombre entier à 5 chiffres attribué de manière unique à chaque produit distinct.
#### Description : Nom du produit (article). Variable nominale.
#### Quantity : Quantité de chaque produit (article) par transaction. Variable numérique.
#### InvoiceDate : Date et heure de la facture. Variable numérique ; jour et heure auxquels chaque transaction a été générée.
#### UnitPrice : Prix unitaire. Variable numérique ; prix du produit à l'unité en livres sterling.
#### CustomerID : Numéro de client. Variable nominale ; nombre entier à 5 chiffres attribué de manière unique à chaque client.
#### Country : Nom du pays. Variable nominale ; nom du pays de résidence de chaque client.

#### Suite à l'analyse prélminiaire du tableau, nous avons remarqué qu'il y a des valeurs négatives dans la colonnes 'UnitPrice', ainsi que des valeurs 'POSTAGE', qui signifie qu'il y a des frais inclut dans la database.

#### Tableau général

In [11]:
online_retail

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

#### df.shape()

In [12]:
online_retail.shape

(541909, 8)

#### df.info() - Comprendre la structure du Dataframe

In [13]:
online_retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

#### df.head() - Comprendre à quoi ressemblent les données, avoir une première inspection visuelle

In [14]:
online_retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

#### df.isna().sum() - Comprendre combien de données sont manquantes

In [15]:
online_retail.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [16]:
online_retail.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

#### df.nunique() - Comprendre combien existe-t-il de valeurs différentes dans chaque colonne

In [17]:
online_retail.nunique()

InvoiceNo      25900
StockCode       4070
Description     4223
Quantity         722
InvoiceDate    23260
UnitPrice       1630
CustomerID      4372
Country           38
dtype: int64

#### df.describe() - Comprendre comment se comportent les variable numériques

In [18]:
online_retail.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

#### df.duplicated().sum() - Vérifier combien on a des doublons

In [19]:
online_retail.duplicated().sum()

np.int64(5268)

#### df.['UnitPrice'].unique() - vérifier l'ensemble des valeurs dans la catégorie 'UnitPrice'

In [20]:
online_retail['UnitPrice'].unique()

array([   2.55,    3.39,    2.75, ...,  933.17, 1714.17,  224.69],
      shape=(1630,))

#### df.['UnitPrice'].nunique() - vérifier le nombre total de valeur dans la catégorie 'UnitPrice'

In [21]:
online_retail['UnitPrice'].nunique()

1630

#### df.['UnitPrice'].min() - vérifier le nombre total de facture d'avoirs

In [22]:
online_retail['UnitPrice'].min()

-11062.06

#### df.[online_retail["UnitPrice"] < 0] - vérifier le nombre d'avoirs et leur montant

In [23]:
online_retail[online_retail["UnitPrice"] < 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

#### df['Credit Note'] = '' - Ajouter les avoirs (trouvé juste ci-dessus) au DataFrame

In [24]:
online_retail['Credit Note'] = ''
online_retail

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Credit Note
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,

#### df?? - Faire apparaitre les valeurs négatives dans la colonne 'Credit Note' du DataFrame

In [25]:
online_retail['Credit Note'] = ''
online_retail

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Credit Note
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,

#### df[df['StockCode'] == 'POST']['Description'].unique() - Comprendre l'ensemble du tableau (de quoi il est composé)

In [29]:
online_retail[online_retail['StockCode'] == 'POST']['Description'].unique()

array(['POSTAGE', nan], dtype=object)

#### df[df['StockCode'] == 'POST']['Description'].unique() - Comprendre l'ensemble du tableau (de quoi il est composé)

In [30]:
online_retail[online_retail['StockCode'] == 'POST']['Description'].unique()

array(['POSTAGE', nan], dtype=object)

In [28]:
online_retail[online_retail['StockCode'] == 'POST']['Description'].unique()

array(['POSTAGE', nan], dtype=object)